ekf_odom:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: false
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # VSLAM odometry (vx, vy, vz, roll, pitch, yaw, and their rates)
    odom0: /visual_slam/tracking/odometry
    odom0_config: [true, true, true,
                   true, true, true,
                   true, true, true,
                   false, false, false,
                   false, false, false]
    odom0_differential: false
    odom0_relative: false

    # IMU orientation + angular velocities + linear accel
    imu0: /oak/imu/data
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]
    imu0_remove_gravitational_acceleration: true

config/navsat_transform.yaml — converts GPS to local frame using IMU & odom

navsat_transform:
  ros__parameters:
    publish_filtered_gps: false
    broadcast_utm_transform: false
    magnetic_declination_radians: 0.0    # set for your locale
    yaw_offset: 1.5707963                # if IMU is 0 when facing North; tune! 
    zero_altitude: true
    use_odometry_yaw: false

