nvblox_node:
  ros__parameters:
    global_frame: map
    odom_frame: odom
    base_frame: base_link

    # Integrators / rates
    voxel_size: 0.05
    esdf_update_rate_hz: 10.0
    mesh_update_rate_hz: 0.0

    # Publish a Nav2-compatible 2D costmap topic
    output_2d_costmap: true
    output_voxel_map: false
